# Generated by Django 5.0.1 on 2024-02-03 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media', models.ManyToManyField(to='backend.media')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('media', models.ManyToManyField(to='backend.media')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField()),
                ('max_players', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.media')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('creations', models.ManyToManyField(related_name='creation_author', to='backend.creation')),
                ('hosted_projects', models.ManyToManyField(related_name='project_host', to='backend.project')),
                ('owned_servers', models.ManyToManyField(related_name='ownership', to='backend.server')),
                ('projects', models.ManyToManyField(related_name='project_teams', to='backend.project')),
                ('servers', models.ManyToManyField(related_name='server_membership', to='backend.server')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='owner',
            field=models.ManyToManyField(related_name='ownership', to='backend.user'),
        ),
        migrations.AddField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(related_name='server_membership', to='backend.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='host',
            field=models.ManyToManyField(related_name='project_host', to='backend.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='project_teams', to='backend.user'),
        ),
        migrations.AddField(
            model_name='creation',
            name='author',
            field=models.ManyToManyField(related_name='creation_author', to='backend.user'),
        ),
    ]
