# Generated by Django 5.0.1 on 2024-02-04 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hosted_projects',
        ),
        migrations.AlterField(
            model_name='server',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.media'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
