# Generated by Django 5.0.1 on 2024-02-05 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_user_projects_remove_user_hosted_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='icon',
            field=models.TextField(default='https://minecom.onrender.com/logo.png'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='creation',
            name='media',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(default='https://static-00.iconduck.com/assets.00/profile-default-icon-512x511-v4sw4m29.png'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.AddField(
            model_name='creation',
            name='media',
            field=models.TextField(default='https://via.placeholder.com/250x150'),
            preserve_default=False,
        ),
    ]
