# Generated by Django 5.0.1 on 2024-02-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_server_icon_remove_creation_media_user_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default="Hello, it's me!"),
            preserve_default=False,
        ),
    ]
